"""Generated documentation: the data dictionary, the ER diagram and the KPI dictionary.

All three are written from sql/schema.yml, the KPI catalog and the warehouse
itself, so they cannot drift from the tables: a blocking check already fails
the build when schema.yml and the warehouse disagree.
"""

import re

import pandas as pd
import yaml

from src.config import DOCS_DIR, SCHEMA_YML

DATA_DICTIONARY = DOCS_DIR / "04_data_dictionary.md"
KPI_DICTIONARY = DOCS_DIR / "05_kpi_dictionary.md"
ER_DIAGRAM = DOCS_DIR / "er_diagram.md"
NOTE = "<!-- Generated by src/docs.py from {source}. Edit the source and rerun the pipeline, not this file. -->"
UNIT_NAMES = {"count": "Count", "pct": "Percentage", "rm": "Ringgit (RM)", "number": "Number"}


def load_spec():
    return yaml.safe_load(SCHEMA_YML.read_text(encoding="utf-8"))


def column_types(con):
    rows = con.execute("""
        SELECT table_schema, table_name, column_name, data_type
        FROM information_schema.columns WHERE table_schema IN ('marts', 'kpi')
    """).fetchall()
    return {(s, t, c): d for s, t, c, d in rows}


def anchor(text):
    return re.sub(r"[^a-z0-9_ -]", "", text.lower()).replace(" ", "-").replace(".", "")


def data_dictionary(con, spec, types):
    lines = [
        "# Data dictionary",
        "",
        NOTE.format(source="sql/schema.yml and the warehouse"),
        "",
        "Every table and column in the reporting layers of the Kelip Bank warehouse: the star schema "
        "(`marts`) and the KPI layer (`kpi`). Types and row counts come from the warehouse after a full run. "
        "The staging layer is described in [the data sources](02_data_sources.md), and how the tables join "
        "is drawn in [the ER diagram](er_diagram.md). All data is synthetic.",
        "",
        "## Contents",
        "",
    ]
    for schema, s in spec["schemas"].items():
        for table in s["tables"]:
            lines.append(f"- [{schema}.{table}](#{anchor(schema + table)})")
    for schema, s in spec["schemas"].items():
        lines += ["", f"## The {schema} schema", "", s["description"]]
        for table, t in s["tables"].items():
            count = con.execute(f"SELECT count(*) FROM {schema}.{table}").fetchone()[0]
            lines += ["", f'<a id="{anchor(schema + table)}"></a>', "", f"### {schema}.{table}", "",
                      t["description"], "",
                      f"- **Grain:** {t['grain']}",
                      f"- **Primary key:** {', '.join(f'`{k}`' for k in t['primary_key'])}",
                      f"- **Rows:** {count:,}"]
            for rel in t.get("relationships", []):
                lines.append(f"- **Joins to:** `{rel['column']}` references `{schema}.{rel['references']}`")
            lines += ["", "| Column | Type | Description |", "|---|---|---|"]
            for column, description in t["columns"].items():
                lines.append(f"| `{column}` | {types.get((schema, table, column), '')} | {description} |")
    DATA_DICTIONARY.write_text("\n".join(lines) + "\n", encoding="utf-8")


def mermaid_type(data_type):
    return re.sub(r"\(.*?\)", "", data_type or "").strip().replace(" ", "_").lower() or "unknown"


def er_diagram(spec, types):
    marts = spec["schemas"]["marts"]["tables"]
    lines = [
        "# ER diagram",
        "",
        NOTE.format(source="the relationships in sql/schema.yml"),
        "",
        "The star schema in the `marts` schema: dimensions (`dim_`) describe who and what, and facts (`fct_`) "
        "record what happened. Each box shows the table's keys; every column is listed in the "
        "[data dictionary](04_data_dictionary.md). Lines run from the table that is referenced (one) to the "
        "table that references it (many), labelled with the joining column. All data is synthetic.",
        "",
        "```mermaid",
        "erDiagram",
    ]
    for table, t in marts.items():
        for rel in t.get("relationships", []):
            target = rel["references"].split(".")[0]
            lines.append(f'    {target} ||--o{{ {table} : "{rel["column"]}"')
    for table, t in marts.items():
        keys = {c: ["PK"] for c in t["primary_key"]}
        for rel in t.get("relationships", []):
            keys.setdefault(rel["column"], []).append("FK")
        lines.append(f"    {table} {{")
        for column, flags in keys.items():
            lines.append(f"        {mermaid_type(types.get(('marts', table, column)))} {column} {', '.join(flags)}")
        lines.append("    }")
    lines += ["```", "", "## Table types", "",
              "| Table | Type | Grain |", "|---|---|---|"]
    kinds = {"dim": "Dimension", "fct_onboarding_funnel": "Fact: accumulating snapshot",
             "fct_ledger_postings": "Fact: transaction", "fct_card_authorisations": "Fact: transaction",
             "fct_marketing_spend": "Fact: periodic (monthly spend by line)"}
    for table, t in marts.items():
        kind = kinds.get(table) or ("Dimension" if table.startswith("dim_") else "Fact: periodic snapshot")
        lines.append(f"| `marts.{table}` | {kind} | {t['grain']} |")
    ER_DIAGRAM.write_text("\n".join(lines) + "\n", encoding="utf-8")


def show_value(value, unit):
    if value is None or pd.isna(value):
        return "no value"
    if unit == "count":
        return f"{value:,.0f}"
    if unit == "number":
        return f"{value:,.1f}"
    if unit == "pct":
        return f"{value * 100:.2f}%" if abs(value) < 0.1 else f"{value * 100:.1f}%"
    if abs(value) >= 1e6:
        return f"RM{value / 1e6:,.1f}m"
    return f"RM{value:,.2f}" if abs(value) < 1000 else f"RM{value:,.0f}"


def kpi_dictionary(con):
    cat = con.execute("SELECT * FROM reference.kpi_catalog ORDER BY kpi_id").df()
    latest = con.execute("""
        SELECT kpi_id, arg_max(value, month_start) AS value, max(month_start) AS month_start
        FROM kpi.kpi_monthly GROUP BY 1
    """).df().set_index("kpi_id")
    sc = con.execute("""
        SELECT kpi_id, plan, status_label FROM kpi.scorecard
        WHERE month_start = (SELECT max(month_start) FROM kpi.scorecard)
    """).df().set_index("kpi_id")
    plans = con.execute("""
        SELECT kpi_id, min(plan_value) AS low, max(plan_value) AS high, count(*) AS months,
               max(note) FILTER (WHERE month_start = (SELECT max(month_start) FROM reference.plan_targets)) AS note
        FROM reference.plan_targets GROUP BY 1
    """).df().set_index("kpi_id")
    families = ["growth", "onboarding", "engagement", "cards", "deposits", "credit", "finance"]
    lines = [
        "# KPI dictionary",
        "",
        NOTE.format(source="data/reference/kpi_catalog.csv, data/reference/plan_targets.csv and the warehouse"),
        "",
        "The 22 KPIs Kelip Bank reports each month: what each one means, how it is calculated, who owns it, "
        "which way is good, and where it comes from. The six marked as scorecard KPIs have a monthly plan and "
        "a red, amber or green status; the rest have a single target. Each KPI answers at least one question "
        "in the [business requirements](01_business_requirements.md). Latest values are for August 2026. "
        "All data is synthetic.",
        "",
        "## Summary",
        "",
        "| ID | KPI | Owner | Unit | Better when | Scorecard | August 2026 |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in cat.itertuples():
        value = latest["value"].get(r.kpi_id)
        month = latest["month_start"].get(r.kpi_id)
        shown = show_value(value, r.unit)
        if month is not None and pd.Timestamp(month).strftime("%Y-%m") != "2026-08":
            shown += f" ({pd.Timestamp(month):%b %Y})"
        lines.append(f"| [{r.kpi_id}](#{r.kpi_id.lower()}) | {r.kpi_name} | {r.owner} | {UNIT_NAMES[r.unit]} | "
                     f"{r.direction.capitalize()} | {'Yes' if r.is_scorecard else ''} | {shown} |")
    for family in families:
        group = cat[cat["family"] == family]
        if group.empty:
            continue
        lines += ["", f"## {family.capitalize()}"]
        for r in group.itertuples():
            if r.is_scorecard and r.kpi_id in plans.index:
                p = plans.loc[r.kpi_id]
                target = (f"Monthly plan, {show_value(p['low'], r.unit)} to {show_value(p['high'], r.unit)} over "
                          f"{int(p['months'])} months; {show_value(sc['plan'].get(r.kpi_id), r.unit)} for "
                          f"August 2026 ({p['note']})")
                status = f", {sc['status_label'].get(r.kpi_id)}"
            else:
                target = f"{show_value(r.target, r.unit)} ({r.target_note})" if not pd.isna(r.target) else "None"
                status = ""
            value = latest["value"].get(r.kpi_id)
            month = latest["month_start"].get(r.kpi_id)
            questions = ", ".join(q.strip() for q in str(r.stakeholder_questions).split(";"))
            lines += [
                "", f'<a id="{r.kpi_id.lower()}"></a>', "", f"### {r.kpi_id} {r.kpi_name}", "",
                f"{r.definition}.", "",
                f"- **Formula:** {r.formula}",
                f"- **Owner:** {r.owner}",
                f"- **Unit:** {UNIT_NAMES[r.unit]}",
                f"- **Better when:** {r.direction}",
                f"- **Amber band:** {r.amber_tolerance:.0%} of plan or target",
                f"- **Target:** {target}",
                f"- **Source:** `{r.source_table}.{r.source_column}`" if " " not in r.source_column
                else f"- **Source:** `{r.source_table}` ({r.source_column})",
                f"- **Answers:** {questions}",
                f"- **Dashboard page:** {r.dashboard_page.replace(';', ', ')}",
                f"- **Latest:** {show_value(value, r.unit)} in {pd.Timestamp(month):%B %Y}{status}",
            ]
    KPI_DICTIONARY.write_text("\n".join(lines) + "\n", encoding="utf-8")


def generate(con):
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    spec = load_spec()
    types = column_types(con)
    data_dictionary(con, spec, types)
    er_diagram(spec, types)
    kpi_dictionary(con)
    return [DATA_DICTIONARY, ER_DIAGRAM, KPI_DICTIONARY]
